Generate new PHP session name with vertical and environment to avoid wrong behaviors
sifophp/SIFO pull request #96
Opened 2021-01-18 12:26 UTC by noelamaya

2021-01-18 12:56 UTC, destebang requested changes

2021-01-18 12:56 UTC, destebang commented on src/Sifo/Session.php
> -				session_start();
Current behavior should be preserved by default, but with the possibility of constructing the session with the name. Otherwise, we break semantic versioning, and may be the applications of the framework users.
As a suggestion, constructor could receive a nullable SessionNameStrategy, if nothing provided it creates sessions without name.

2021-01-18 13:11 UTC, noelamaya commented on src/Sifo/Session.php
> -				session_start();
I agree with you, but:
1. This is a security issue and we shouldn't let users continue to be affected by that security issue.
2. We have to change all uses of the getInstance(), more than 100.
Maybe we have to update to a major version?

2021-01-19 14:44 UTC, GicuGix commented on src/Sifo/Session/SessionEnvironmentStrategy.php
> +        $instance_environment_initial = $_SERVER['APP_ENV'][0] ?? '';
May be is better to have a default value for `$instance_environment_initial` not an empty string.

2021-01-19 14:45 UTC, GicuGix commented on src/Sifo/Session/SessionEnvironmentStrategy.php
> +        session_name($instance_session_name);
`session_name("SSID_{$instance_environment_initial}_{$vertical_instance}");`

2021-01-19 14:48 UTC, GicuGix reviewed
🚀

2021-01-19 15:21 UTC, noelamaya commented on src/Sifo/Session/SessionEnvironmentStrategy.php
> +        $instance_environment_initial = $_SERVER['APP_ENV'][0] ?? '';
If you have a default value you can't ensure if this environment exists or not.

2021-01-19 15:24 UTC, noelamaya commented on src/Sifo/Session/SessionEnvironmentStrategy.php
> +        session_name($instance_session_name);
I don't find any inconvenience to having it like this, and when I was debugging it helped me to see the session name to set.

2021-01-19 16:33 UTC, destebang approved these changes
👍🏼  LGTM

2021-01-20 15:37 UTC, p0lemic approved these changes

2021-01-20 15:37 UTC, merged